apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lazylibrarian
  namespace: lazylibrarian
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: lazylibrarian.pkya.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lazylibrarian-saruman
                port:
                  number: 80
